### PR TITLE
<zerorpc.events.Event object at 0x7f1df6565dc0>)> failed with KeyError

### PR DESCRIPTION
**Pull request by BarryPaneer**
## Summary of changes

execute command: composer update ( in project: laravel-zerorpc )

we got an error:
    - The requested package 0rpc/zerorpc-php 1.2.4 exists as 0rpc/zerorpc-php[1.2.1, 1.2.2, dev-master, 1.2.3] but these are rejected by your constraint.

I think, because the newest release version is 1.2.4 and the version in composer.json is 1.2.3, so we need to update it.

## How to Test
1) in test, you could take my github url ( git@github.com:BarryPaneer/zerorpc-php.git ) instead.
2) cd  laravel-zerorpc
3) composer update

/fyi: @zhangjustin , @mark-juwai : Please review.

### CODE REVIEW

**Review by mark-juwai — APPROVED** [review]

**Review by zhangjustin — APPROVED** [review]

**Comment by BarryPaneer** [comment]
please, merge it. thx.

**Comment by BarryPaneer** [comment]
and please rebuild the tag again, thx.

https://github.com/juwai/zerorpc-php/releases/tag/1.2.4

**Comment by BarryPaneer** [comment]
I have no permission.

**Comment by mark-juwai** [comment]
There might be some issue with rebuild. Let's just increase it.

**Comment by BarryPaneer** [comment]
ok.   
so 1.2.5

**Comment by mark-juwai** [comment]
Created, please check.

**Comment by BarryPaneer** [comment]
ok. it's works.

**Pull request merged**
